// Auto-generated by Figma Make — version: v1.0.0
// UI Primitives Barrel Export

export * from './UIButton';
export * from './UICard';
export * from './UIInput';
export * from './UIBadge';
export * from './UISkeleton';
export * from './UIAvatar';
export * from './UIDropdownMenu';
export * from './UISelect';
export * from './UILabel';
export * from './UISlider';
export * from './UITabs';

// Compatibility aliases for Figma imports (without "UI" prefix)
export { UIButton as Button, buttonVariants } from './UIButton';
export { 
  UICard as Card,
  UICardHeader as CardHeader,
  UICardFooter as CardFooter,
  UICardTitle as CardTitle,
  UICardAction as CardAction,
  UICardDescription as CardDescription,
  UICardContent as CardContent,
} from './UICard';
export { UIInput as Input } from './UIInput';
export { UIBadge as Badge, badgeVariants } from './UIBadge';
export { UISkeleton as Skeleton } from './UISkeleton';
export { UIAvatar as Avatar, UIAvatarImage as AvatarImage, UIAvatarFallback as AvatarFallback } from './UIAvatar';
export {
  DropdownMenu,
  DropdownMenuTrigger,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
} from './UIDropdownMenu';
export {
  Select,
  SelectTrigger,
  SelectValue,
  SelectContent,
  SelectItem,
} from './UISelect';
export { UILabel as Label } from './UILabel';
export { UISlider as Slider } from './UISlider';
export {
  UITabs as Tabs,
  UITabsList as TabsList,
  UITabsTrigger as TabsTrigger,
  UITabsContent as TabsContent,
} from './UITabs';

