// Auto-generated by Figma Make — version: v1.0.0
// UI Primitives Barrel Export

export * from './UIButton';
export * from './UICard';
export * from './UIInput';
export * from './UIBadge';
export * from './UISkeleton';
export * from './UIAvatar';

