// Auto-generated by Figma Make — version: v1.0.0
"use client";

import * as React from "react";
import { cn } from "../utils/cn";

// Variants: default (pulse animation)
const UISkeleton = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(
  ({ className, ...props }, ref) => {
    return (
      <div
        ref={ref}
        data-slot="skeleton"
        className={cn("animate-pulse rounded-md bg-primary/10", className)}
        {...props}
      />
    );
  }
);

UISkeleton.displayName = "UISkeleton";

export { UISkeleton };
