-- NOTE: This migration is not needed!
-- The /api/bootstrap endpoint uses service role key to create initial org/membership.
-- This is the correct approach because:
--   1. It's a one-time administrative operation
--   2. User has no memberships yet (chicken-and-egg problem)
--   3. Existing RLS policies in 002_rls_policies.sql handle all other operations
--
-- The /api/bootstrap endpoint:
--   - Authenticates user via session cookie (ensures they're logged in)
--   - Uses service role key to bypass RLS for initial org creation
--   - This is a controlled, audited operation (logged, limited scope)
--
-- All other operations (tracks, jobs, etc.) use proper RLS via user sessions.

